In [1]:
import  numpy as np
import pandas as pd
import  matplotlib.pyplot as plt

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a = np.arange(1,20, 5)
a


array([ 1,  6, 11, 16])

In [4]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr_r = np.linspace(1,5,10)
arr_r

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

PYTHON NUMPY INDEXING

In [7]:
arr_rr = np.array([[1,2,3], [4,5,6]])
arr_rr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(arr_rr[0])

[1 2 3]


In [9]:
print(arr_rr[1])

[4 5 6]


In [10]:
print(arr_rr[0][2])

3


In [11]:
print(arr_rr[0,2])

3


ARRAY SLICING

In [12]:
print(arr_rr[0:1,2:])

[[3]]


In [13]:
arr_max = np.array([[3,4,5,6,7,9],[1,0,0,1,0,1],[1,3,5,7,9,1],[2,4,6,8,1,3]])
arr_max

array([[3, 4, 5, 6, 7, 9],
       [1, 0, 0, 1, 0, 1],
       [1, 3, 5, 7, 9, 1],
       [2, 4, 6, 8, 1, 3]])

In [14]:
arr_max[0:1]

array([[3, 4, 5, 6, 7, 9]])

In [15]:
arr_max[0:2, 1:4]

array([[4, 5, 6],
       [0, 0, 1]])

In [16]:
arr_max[1:4,0:3]

array([[1, 0, 0],
       [1, 3, 5],
       [2, 4, 6]])

In [17]:
#Create an array with data type string
arr = np.array([1,2,3,4], dtype ='S')
print(arr)
print (arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [18]:
#Change data type from float to integer
arr = np.array([1.1, 2.1,3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


RESHAPING ARRAYS

In [19]:
#Reshape to 2D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
#Reshape to 3D
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


ARRAY FLATENING

In [21]:
newarr1 = newarr.flatten()
print(newarr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg
rng = gen(pcg())
rng.normal(size = (5, 5))




array([[ 1.03683958, -2.39827417,  0.33354037, -0.59078132,  1.61112728],
       [ 1.48002471, -0.65031563, -1.58036885, -0.01136907,  0.38194406],
       [-1.12153641,  1.65873809,  0.05912273,  0.28409098,  0.19352525],
       [-0.06091663, -0.3549658 , -0.66079833,  0.09961334,  0.628876  ],
       [ 0.46882927, -2.01019264, -0.95243406,  0.51519683, -2.62382759]])

In [27]:
rng = gen(pcg(seed=100))
rng.normal(size = (5, 5))

array([[-1.15754965,  0.2897558 ,  0.78085407,  0.54397364, -0.96138264],
       [ 1.07100867,  0.70145566,  0.70497346,  0.7450626 ,  1.10434724],
       [ 2.2429724 , -0.61149312,  0.04721118,  1.75423468, -1.33797987],
       [ 0.32557447, -0.68911772, -0.01982181,  0.47475325, -1.93110142],
       [-0.99247828, -1.40547108, -0.23109551, -0.68884708,  1.51510578]])

In [31]:
rng1 = gen(pcg())
rng1.random(size = (5, 5))

array([[0.88909868, 0.27171927, 0.16608853, 0.50396289, 0.03491617],
       [0.1464407 , 0.89608657, 0.63269025, 0.92621104, 0.28592121],
       [0.76425077, 0.90198452, 0.62026682, 0.39982655, 0.18900355],
       [0.74558781, 0.41634812, 0.99246413, 0.50572445, 0.12693509],
       [0.05630181, 0.0820984 , 0.93137809, 0.27257685, 0.4299311 ]])

In [34]:
rng1 = gen(pcg())
rng1.integers(low =0, high = 10, size = (2,3))

array([[3, 8, 5],
       [0, 5, 8]])

In [35]:
rng2 = gen(pcg())
rng2.standard_normal(10)

array([-0.61988569,  0.60608615, -0.894291  , -0.28560083,  1.75027448,
        0.16993315,  0.46878367,  0.48102481,  0.39516833,  1.44288706])