In [1]:
import numpy as np
rng = np.random.default_rng()

In [3]:
rng.random(size = (2,4))

array([[0.10534782, 0.94828847, 0.63912475, 0.82366771],
       [0.24361301, 0.59712233, 0.85450521, 0.5359899 ]])

In [8]:
rng.normal(size = (3,5))

array([[-0.76635186, -1.13884875,  0.60638256, -0.26116632, -1.04674893],
       [ 0.47690296,  1.33134278,  0.56137461,  1.34054717,  1.86095445],
       [ 0.99543668,  1.20839936,  0.91609913,  1.0306231 ,  0.12428278]])

In [9]:
rng.integers(low = 0, high = 20, size = (4,5))

array([[12, 10, 10, 13,  2],
       [ 7,  2,  4, 15, 17],
       [13, 11,  7,  4,  1],
       [ 3, 16,  2,  8, 19]])

In [10]:
rng.integers(low = 0, high = 20, size = (4,5))

array([[ 3, 17, 17,  2,  5],
       [14,  0,  6,  8,  3],
       [10, 19,  1,  2, 18],
       [17,  7, 13, 19,  0]])

In [16]:
rng1 = np.random.default_rng(seed = 100)
arr1= rng1.integers(low = 0, high = 20, size = (4,5))
arr1


array([[15, 16,  2, 11,  1],
       [ 5,  8,  0, 11, 19],
       [18, 11,  8, 15, 18],
       [18,  0, 13, 14,  3]])

In [19]:
arr2 = rng1.integers(low = 0, high = 20, size = (4,5))
arr2

array([[12, 12,  3,  1, 16],
       [ 5, 16, 13,  2,  0],
       [ 2, 16,  9,  1,  4],
       [10, 16, 10, 12,  4]])

In [2]:
#Function to reverse a lsit without using the built-in reverse method

def reverse_list(input_list):
    left = 0
    right = len(input_list)-1

    while left< right:
        input_list[left], input_list[right] = input_list[right], input_list[left]

        left +=1
        right -=1

    return input_list


my_list = [1,3,5,6,7,8,9]
result = reverse_list(my_list)
print(result)

[9, 8, 7, 6, 5, 3, 1]


In [1]:
#Function to return the count of vowels;
def count_vowels(input_string):
    vowels = "aeiou"
    return sum(1 for char in input_string.lower() if char in vowels)

my_string = "My name is Jane"
print(count_vowels(my_string))

5


In [3]:
#Defining the same function but with a longer approach

def count_vowels(input_string):
    vowels = "aeiou"
    count = 0

    for char in input_string.lower():
        if char in vowels:
            count +=1
    return count
my_string = "My name is Jane"
mylonger_string = "This is a brand new product, it requires much attention and time in order to be fully processed. Thank you"
print(count_vowels(my_string))
print(count_vowels(mylonger_string))    

5
32


In [4]:
# Function to return a dictionary containing mean, max, min and std from a numpy 1D array

import numpy as np
def array_stats(arr):
    dict = {
        "mean" : np.mean(arr),
        "min" : np.min(arr),
        "max" : np.max(arr),
        "std" : np.std(arr)
    }
    return dict

arr = np.array([1,3,44,56,8,9,12,4,7])
print(array_stats(arr))

{'mean': np.float64(16.0), 'min': np.int64(1), 'max': np.int64(56), 'std': np.float64(18.65475810617763)}


In [9]:
# Function to check whether a phrase is a palindrome

def is_palindrome(input_string):
    #Clean the input string
    cleaned_string = input_string.replace(" ", "").lower()
    #Check for palindrome
    return cleaned_string == cleaned_string[::-1]
 #Test the function
string1= 'Race Car'
print(is_palindrome(string1))
string2 = "Hello"
string3 = "A man  a plan a canal  Panama"
print(is_palindrome(string2))
print(is_palindrome(string3))

True
False
True


In [13]:
# A function to normalize a Numpy array input

def normalize_array(arr):
    mini = np.min(arr)
    maxi = np.max(arr)
    x = np.array(arr)
    normalised = (x-mini)/(maxi - mini)
    return normalised

arr = [2,4,5,7,8,10,11,14,24]
print(normalize_array(arr))

[0.         0.09090909 0.13636364 0.22727273 0.27272727 0.36363636
 0.40909091 0.54545455 1.        ]


In [15]:
# A function to generate fibonacci numbers

def fibonacci(n):
    if n<=0:
        return []
    if n<=1:
        return [0]
    fib_list = [0,1]

    while len(fib_list)<n:
        next_value = fib_list[-1] + fib_list[-2]
        fib_list.append(next_value)
    return fib_list    


#Example
print(fibonacci(7))

[0, 1, 1, 2, 3, 5, 8]
